version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.2-stretch
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
        keys:
          # "composer.lock" can be used if it is committed to the repo
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
        key: v1-dependencies-{{ checksum "composer.json" }}
        paths:
          - ./vendor

      # Run tests
      - run: phpdbg -qrr ./vendor/bin/phpunit --coverage-clover coverage.xml
      - codecov/upload:
          file: coverage.xml
